apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: prod-database-secret
  namespace: prod
spec:
  encryptedData:
    password: AgCrkXJSsqZCLlVo9WMiI9rQ6uFPkxzUn0YGZ6IPZbSDpgmRjtefvZWjQvliL7FFr6lHjDXLQ15Cp/CQ88boknmVjnoH5y4i9ilokN/TaPFHlGWzZsa0FW4g+HemnRw4OfQyYwkORFXfcqP0B9QvqkqNB7HVRubxnnL/NMMFzntfCoRouHpaI2pfJqQBSjMG5wYg9GuW/ISkEYd9Rfgt8pMu5Ht2X29TzNweXf82nvwN/XIaDKXuz2sd6uPKkZwGsVvyK1ii7pCFu4nk6cLE5+S8hJQlCIp5iD5uY5caS2gI8gpUtTCBic//6NeOfUIUzKCjX5l83bBeYKFlQ1QMIilvXW/d94TEuFTTcD0SpKQTVn3VC6s/GiG0IdVsSe42y0JsxSxXwF7c5023gbPQGhLidfUfYjhecH+6jw096/Vyl2OfGCDl1t643Qd4pjZUgpZRmB4aKhkCD7xm0Qong0Lof5Q+1hz6LPlM9MllHwm4E+5bBM4iAguN048zprKGBvS/UNfgdfMpkjN91WTt7rz+sCXGaheSzx9KeYFiifmb5ls8duvbU9EgdoVRodZruHNcN4MPjC6uiygp62OFyay/At2CY/fDg6rPn87svfIkpAPYHfckunveL4ZLY3nGkedGrdb3fjpR+OKmOc7IT/XZHRmjhWgslvkCuXbjeAZL2rpmnM5grdnzztUwXCr6cRNgnWTO
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: prod-database-secret
      namespace: prod

