apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
namePrefix: prod-

resources:
- ../../base

patchesStrategicMerge:
- prod_settings.yml
- replicas.yml

images:
- name: docker.io/javadza/environment-promotion
  newName: docker.io/javadza/environment-promotion
  newTag: 2022-07-05-63a6912
