apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-

resources:
- ../../base

patchesStrategicMerge:
- dev_settings.yml
- replicas.yml

images:
- name: docker.io/javadza/environment-promotion
  newTag: "9.02.01"