---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        env:
        - name: VERSION
          valueFrom:
            fieldRef:
              fieldPath: webserver-simple
              resource: image