name: Prod Auto-PR
on:
  push:
    branches: ['prod']

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          branch: prod
          delete-branch: true
          assignees: JavadZahrabi
          reviewers: JavadZahrabi
