name: Staging Auto-PR
on:
  push:
    branches: ['staging']

jobs:
  pull-request:
    name: Open PR to master from staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "master"
        pr_title: "Deploy to staging"
        pr_body: "An automated PR from staging"
        pr_reviewer: "JavadZahrabi"
        pr_draft: true
        github_token: ${{ secrets.ACTIONS_TOKEN }}